name: Build and Push to Docker Hub

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          # YAHAN APNA ASLI USERNAME LIKHEIN (Bina brackets ke)
          username: shehzarubaid 
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # YAHAN BHI APNA ASLI USERNAME LIKHEIN
          tags: shehzarubaid/flux-runpod:latest